# Generated by Django 6.0.6 on 2026-08-21 21:03

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_savedhostel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='id_document',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='id_document'),
        ),
        migrations.AlterField(
            model_name='hostelimage',
            name='image',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='image'),
        ),
    ]
