# Generated by Django 6.0.6 on 2026-08-22 11:46

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_agent_id_document_alter_hostelimage_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='passport',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='passport'),
        ),
        migrations.AlterField(
            model_name='agent',
            name='id_document',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='id_document (NIN)'),
        ),
    ]
