# Generated by Django 6.0.6 on 2026-08-22 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_agent_passport_alter_agent_id_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='business_name',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
