# Generated by Django 6.0.6 on 2026-08-22 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_agent_business_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='matric_no',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
