# Generated by Django 6.0.6 on 2026-08-22 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_student_matric_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='hostel',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
    ]
